from setuptools import setup, find_packages

setup(
    name="heurist-viz",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "click>=8.0.0",
        "openai>=1.0.0",
        "python-dotenv>=0.19.0",
        "tiktoken>=0.3.0",
        "fvalues>=0.0.4",
        "transformers>=4.0.0",
        "structlog>=22.1.0",
        "nest-asyncio>=1.5.6",
        "questionary>=1.10.0",
        "rich>=12.0.0",
        "diskcache>=5.4.0",
        "aiohttp>=3.8.0",
        "pydantic<2",
        "typing-extensions>=4.0.0",
        "numpy>=1.20.0",
        "torch>=1.8.0",
        "accelerate>=0.20.0",
        "python-ulid>=1.1.0",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "websockets>=10.0",
        "watchfiles>=0.18.0",
        "more-itertools>=8.0.0",
        "httpx>=0.24.0",
        "jinja2>=3.0.0",
        "python-multipart>=0.0.5",
        "typing-inspect>=0.8.0",
        "defopt>=6.0.0",
        "backoff>=2.0.0",
        "docstring-parser>=0.15",
        "ipython>=8.0.0",
        "termcolor>=2.0.0",
        "pandas>=1.0.0",
        "tenacity>=8.0.0",
        "cattrs>=22.2.0",
        "dataclasses-json>=0.5.7",
        "types-requests>=2.28.0",
        "merge-args>=0.1.4",
        "faker",
        "matplotlib",
        "nltk",
        "numerizer",
        "python-Levenshtein",
        "rouge-metric",
        "ruamel.yaml",
        "scikit-learn",
        "thefuzz",
        "tqdm",
        "protobuf",
        "sentencepiece",
        "pytest>=7.0.0",
        "black>=22.0.0",
        "flake8>=4.0.0",
        "mypy>=0.900",
        "isort>=5.10.0",
        "pytest-asyncio>=0.20.0",
        "pytest-cov>=4.0.0",
        "pytest-timeout>=2.1.0",
        "autoflake",
        "pre-commit",
        "pylint",
        "pytest-mock",
        "gorilla>=0.4.0",
        "requests>=2.28.0",
        "pyyaml>=6.0.0",
    ],
    
    author="Jorge RE",
    author_email="jorge@heurist.ai",
    description="Heurist Trace Visualizer",
    long_description="A tool for visualizing agent interactions, code derived from the ICE repo",
    long_description_content_type="text/markdown",
    url="https://github.com/jorge-re/heurist-viz",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
) 